"""
Django settings for ids_web project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.environ.get("IDS_DEBUG", "1") == "1"

_DEV_KEY = "django-insecure-b6)pxssa57ra_pvell3dsn08(xb^2-g4urh66+&93k6^8irgy^"
SECRET_KEY = os.environ.get("IDS_SECRET_KEY", "" if not DEBUG else _DEV_KEY)

if not SECRET_KEY:
    raise RuntimeError(
        "IDS_SECRET_KEY must be set when IDS_DEBUG=0. Generate one with:\n"
        "  python -c \"from django.core.management.utils import get_random_secret_key as k; print(k())\""
    )

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = os.environ.get("IDS_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # "3 minutes ago" beside each run's timestamp on the history page.
    'django.contrib.humanize',
    'django.contrib.staticfiles',
    'predictor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ids_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ids_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# MySQL is used when IDS_DB_ENGINE=mysql and credentials are supplied; otherwise
# the app falls back to SQLite so it runs on a fresh clone with no database
# server at all. Nothing in the app depends on which one is active.
if os.environ.get("IDS_DB_ENGINE", "sqlite").lower() == "mysql":
    import pymysql

    pymysql.install_as_MySQLdb()

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ.get("IDS_DB_NAME", "ids_nids"),
            "USER": os.environ.get("IDS_DB_USER", "root"),
            "PASSWORD": os.environ.get("IDS_DB_PASSWORD", ""),
            "HOST": os.environ.get("IDS_DB_HOST", "127.0.0.1"),
            "PORT": os.environ.get("IDS_DB_PORT", "3306"),
            "OPTIONS": {"charset": "utf8mb4"},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# App-level static files (predictor/static/) are found by the app-dirs finder.
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Where the trained models and Processed_Data/ live. Left as None, predictor.ml
# walks up from this file looking for webapp_data/ or c_filesnew/.
IDS_DATA_ROOT = os.environ.get("IDS_DATA_ROOT") or None

# Prediction history is an append-only JSONL log (see predictor/history_log.py)
# rather than a database table. Point IDS_HISTORY_LOG at a mounted disk to keep
# history across deploys -- on an ephemeral filesystem the default path lasts
# only as long as the container, the same as db.sqlite3 beside it.
HISTORY_LOG_PATH = os.environ.get("IDS_HISTORY_LOG") or (BASE_DIR / "logs" / "predictions.jsonl")

# Uploaded datasets are held in memory up to this size before spilling to a
# temp file; batch scoring reads the whole frame anyway.
DATA_UPLOAD_MAX_MEMORY_SIZE = 256 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 256 * 1024 * 1024


# --- Production hardening -------------------------------------------------
# Enabled together via IDS_SECURE=1 so local HTTP development is unaffected.
# Turn it on only once the deployment actually terminates TLS, or every
# request will redirect to https:// and the site will appear to hang.
if os.environ.get("IDS_SECURE", "0") == "1":
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get("IDS_CSRF_TRUSTED_ORIGINS", "").split(",") if o
]

# Render injects the assigned hostname. Picking it up automatically means a
# deploy does not fail with DisallowedHost just because the URL was not known
# ahead of time.
_render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if _render_host:
    if _render_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_render_host)
    _render_origin = f"https://{_render_host}"
    if _render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_render_origin)

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}
