# Generated by Django 6.0.8 on 2026-08-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('manual', 'Manual entry'), ('batch', 'Dataset upload')], db_index=True, max_length=10)),
                ('model_key', models.CharField(max_length=40)),
                ('model_name', models.CharField(max_length=60)),
                ('predicted_label', models.CharField(blank=True, max_length=60)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('attack_count', models.PositiveIntegerField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('macro_f1', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'prediction',
                'verbose_name_plural': 'predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
